version: 2.0
jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.272-browsers
#        auth:
#          username: mydockerhub-user
#          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: "Run tests"
          command: ./mvnw test
          when: always
